### ISSUE TITLE
Integration of  Lineage data in the Explorer

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#263]
Part of Work Package 1 
Requirements from the Proposal:
1. Integration of lineage information in collaboration with NML. 
2. Faceted search for records containing VoCs. 
3. Faceted search for records corresponding to lineage(s) of interest. 
4. Support for both lineage tree designations and WHO Greek designations. 
--> additional metadata/labeling for each sequence, (E.g. Which lineage tree the sequence belongs to and the WHO easy-to-understand Greek designations for VoCs)

Priority 1 from the new work packages: to be taken as after the standing production issues.

**Comment by sifavahora** [comment]
- [ ] Update metadata for Lineage fields and observe system reaction 
- [ ] Update the schema - add new test field to observe system reaction 
- [ ] setup the infra for the app/service 
- [ ] fetch the data from ViralAI cloud 
- [ ] spike to figure out the integration of that data Song/Maestro
- [ ] Integrate the backend changes to UI/Arranger
- [ ] Add the columns to Singularity tsv creation list
- [ ] Ensure the Documentation is in place for Lineage Integration

**Comment by scottcain** [comment]
Live on production!
