### ISSUE TITLE
Add new fields to VirusSeq portal - all layers 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#55]
There will be additional fields added to the virus-seq dataset: 
- 4 new, optional fields. 
- the isolate field is no longer required, thus muse cannot rely on it to associate payloads/files. 
- 1 new required field `fasta_header_name`.  This field should replace all functionality of the `isolate` field. 

## Steps to Update
- [ ] Data harmonizer template update
- [x] Song - https://github.com/cancogen-virus-seq/metadata-schemas/issues/4
- [x] ES mapping - https://github.com/cancogen-virus-seq/roadmap/issues/26
- [ ] Muse update needed 
  - https://github.com/cancogen-virus-seq/muse/issues/74  [fields]
  - https://github.com/cancogen-virus-seq/muse/issues/76 [isolate --> header change)
- [x] Singularity update needed - https://github.com/cancogen-virus-seq/singularity/issues/8
- [x] Payload migration - https://github.com/cancogen-virus-seq/roadmap/issues/27
- At this point all deploys are done, and need to do a reindex. Portal in maintenance with  down time. 
- [x] UI deployment with updated new fields - https://github.com/cancogen-virus-seq/portal/issues/56
